### ISSUE TITLE
Graphql is missing or what?

### ISSUE THREAD

**Issue by dongalor** [bitquery/explorer#61]
Hello, guys!
\
Trying to set up this explorer. Application runs but when I open it in browser loaders appear, but nothing happens. In logs I can see, that it can't access graphql server. Do I need to set it up separately or it's supposed that we need to use bitquery's graphql (found it in Dockerfile env variables).

Thank you for you help in advance!

**Comment by crox-safe** [comment]
You need to edit [.env.example](https://github.com/bitquery/explorer/blob/master/.env.example) with the GraphQL endpoint

Here's an example:

`# Website url
BITQUERY_PROJECT_URL="https://bitquery.io"

# Path to server storing images.
BITQUERY_IMAGES="https://bitquery.io/wp-content/uploads/2020/09"

# Path to GrahpQL server
BITQUERY_GRAPHQL="https://graphql.bitquery.io"

ANALYTICS=false

# Key for access API ( passed in X-API-KEY header )
EXPLORER_API_KEY="API-KEY"
`
